# fly.toml app configuration file generated for bigu-backend-nest on 2024-09-17T17:30:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bigu-api"
primary_region = "gig"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_001
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024
